{{- if .Values.services.makelineservice.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: makelineservice
  namespace: {{ .Values.global.namespace }}
  labels:
    app: make-line-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: make-line-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: make-line-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: make-line-service
spec:
  replicas: {{ .Values.services.makelineservice.replicas }}
  selector:
    matchLabels:
      app: make-line-service
  template:
    metadata:
      labels:
        app: make-line-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ .Values.services.makelineservice.dapr.appId | quote }}
        dapr.io/app-port: {{ .Values.services.makelineservice.dapr.appPort | quote }}
        dapr.io/log-level: {{ .Values.services.common.dapr.logLevel | quote }}
    spec:
      containers:
      - name: make-line-service
        image: {{ .Values.services.makelineservice.image.repository }}:{{ .Values.services.common.image.tag }}
        imagePullPolicy: {{ .Values.services.common.image.pullPolicy }}
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.services.common.resources.requests.cpu }}
            memory: {{ .Values.services.common.resources.requests.memory }}
          limits:
            cpu: {{ .Values.services.common.resources.limits.cpu }}
            memory: {{ .Values.services.common.resources.limits.memory }}
        startupProbe:
          httpGet:
            path: /probes/healthz
            port: 80
          failureThreshold: 6
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /probes/livez
            port: 80
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /probes/readyz
            port: 80
          periodSeconds: 5
{{- end }}
