{{- if .Values.services.receiptgenerationservice.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: receiptgenerationservice
  namespace: {{ .Values.global.namespace }}
  labels:
    app: receipt-generation-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: receipt-generation-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-generation-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: receipt-generation-service
spec:
  replicas: {{ .Values.services.receiptgenerationservice.replicas }}
  selector:
    matchLabels:
      app: receipt-generation-service
  template:
    metadata:
      labels:
        app: receipt-generation-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ .Values.services.receiptgenerationservice.dapr.appId | quote }}
        dapr.io/app-port: {{ .Values.services.receiptgenerationservice.dapr.appPort | quote }}
        dapr.io/log-level: {{ .Values.services.common.dapr.logLevel | quote }}
    spec:
      containers:
      - name: receipt-generation-service
        image: {{ .Values.services.receiptgenerationservice.image.repository }}:{{ .Values.services.common.image.tag }}
        imagePullPolicy: {{ .Values.services.common.image.pullPolicy }}
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.services.common.resources.requests.cpu }}
            memory: {{ .Values.services.common.resources.requests.memory }}
          limits:
            cpu: {{ .Values.services.common.resources.limits.cpu }}
            memory: {{ .Values.services.common.resources.limits.memory }}
{{- end }}
