{{- if .Values.services.ui.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ .Values.global.namespace }}
  labels:
    app: ui
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ui
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Values.global.namespace }}
  labels:
    app: ui
spec:
  replicas: {{ .Values.services.ui.replicas }}
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      {{- if .Values.services.common.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.services.common.image.pullSecrets }}
        - name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- $commonResources := .Values.services.common.resources }}
      {{- $uiResources := .Values.services.ui.resources | default dict }}
      {{- $uiRequests := $uiResources.requests | default dict }}
      {{- $uiLimits := $uiResources.limits | default dict }}
      containers:
      - name: ui
        image: {{ .Values.services.ui.image.repository }}:{{ .Values.services.common.image.tag }}
        imagePullPolicy: {{ .Values.services.common.image.pullPolicy }}
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: VITE_MAKELINE_BASE_URL
          value: {{ .Values.services.ui.env.VITE_MAKELINE_BASE_URL | quote }}
        - name: VITE_ACCOUNTING_BASE_URL
          value: {{ .Values.services.ui.env.VITE_ACCOUNTING_BASE_URL | quote }}
        resources:
          requests:
            cpu: {{ default $commonResources.requests.cpu $uiRequests.cpu }}
            memory: {{ default $commonResources.requests.memory $uiRequests.memory }}
          limits:
            cpu: {{ default $commonResources.limits.cpu $uiLimits.cpu }}
            memory: {{ default $commonResources.limits.memory $uiLimits.memory }}
{{- end }}
