{{- if .Values.services.virtualworker.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: virtualworker
  namespace: {{ .Values.global.namespace }}
  labels:
    app: virtual-worker
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: virtual-worker
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-worker
  namespace: {{ .Values.global.namespace }}
  labels:
    app: virtual-worker
spec:
  replicas: {{ .Values.services.virtualworker.replicas }}
  selector:
    matchLabels:
      app: virtual-worker
  template:
    metadata:
      labels:
        app: virtual-worker
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ .Values.services.virtualworker.dapr.appId | quote }}
        dapr.io/app-port: {{ .Values.services.virtualworker.dapr.appPort | quote }}
        dapr.io/log-level: {{ .Values.services.common.dapr.logLevel | quote }}
        dapr.io/config: {{ default "reddog.configuration" .Values.dapr.configuration.name | quote }}
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
        dapr.io/sidecar-cpu-request: {{ .Values.services.common.dapr.resources.requests.cpu | quote }}
        dapr.io/sidecar-memory-request: {{ .Values.services.common.dapr.resources.requests.memory | quote }}
        dapr.io/sidecar-cpu-limit: {{ .Values.services.common.dapr.resources.limits.cpu | quote }}
        dapr.io/sidecar-memory-limit: {{ .Values.services.common.dapr.resources.limits.memory | quote }}
    spec:
      containers:
      - name: virtual-worker
        image: {{ .Values.services.virtualworker.image.repository }}:{{ .Values.services.common.image.tag }}
        imagePullPolicy: {{ .Values.services.common.image.pullPolicy }}
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: DAPR_HTTP_PORT
          value: "3500"
        resources:
          requests:
            cpu: {{ .Values.services.common.resources.requests.cpu }}
            memory: {{ .Values.services.common.resources.requests.memory }}
          limits:
            cpu: {{ .Values.services.common.resources.limits.cpu }}
            memory: {{ .Values.services.common.resources.limits.memory }}
        startupProbe:
          httpGet:
            path: /healthz
            port: 80
          failureThreshold: 6
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /livez
            port: 80
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 80
          periodSeconds: 5
          timeoutSeconds: 3
{{- end }}
