{{- if .Values.dapr.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: virtualworker.cron
  namespace: {{ .Values.global.namespace }}
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 5s"
scopes:
  - {{ .Values.services.virtualworker.dapr.appId | quote }}
{{- end }}
