{{- if and .Values.dapr.enabled (.Values.services.receiptgenerationservice.binding.enabled | default false) }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.binding.receipt
  namespace: {{ .Values.global.namespace }}
spec:
  type: bindings.localstorage
  version: v1
  metadata:
  - name: rootPath
    value: /tmp/receipts
scopes:
  - {{ .Values.services.receiptgenerationservice.dapr.appId | quote }}
{{- end }}
