{{- if .Values.dapr.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.pubsub
  namespace: {{ .Values.global.namespace }}
spec:
  type: pubsub.{{ .Values.dapr.pubsub.type }}
  version: v1
  metadata:
  {{- if .Values.dapr.pubsub.metadata }}
  {{- toYaml .Values.dapr.pubsub.metadata | nindent 2 }}
  {{- else }}
  - name: redisHost
    value: {{ .Values.dapr.pubsub.host }}:{{ .Values.dapr.pubsub.port }}
    {{- if .Values.dapr.pubsub.password }}
  - name: redisPassword
    value: {{ .Values.dapr.pubsub.password | quote }}
    {{- end }}
  {{- end }}
scopes:
  - {{ .Values.services.orderservice.dapr.appId | quote }}
  - {{ .Values.services.makelineservice.dapr.appId | quote }}
  - {{ .Values.services.loyaltyservice.dapr.appId | quote }}
  - {{ .Values.services.receiptgenerationservice.dapr.appId | quote }}
  - {{ .Values.services.accountingservice.dapr.appId | quote }}
{{- end }}
