{{- if .Values.dapr.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.secretstore
  namespace: {{ .Values.global.namespace }}
spec:
  type: secretstores.{{ .Values.dapr.secretStore.type }}
  version: v1
  metadata:
  {{- if .Values.dapr.secretStore.metadata }}
  {{- toYaml .Values.dapr.secretStore.metadata | nindent 2 }}
  {{- else }}
  - name: namespace
    value: {{ .Values.global.namespace | quote }}
  {{- end }}
{{- end }}
