apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: reddog-retail
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: ui
        dapr.io/config: reddog.config
    spec:
      containers:
        - name: ui
          image: ghcr.io/ahmedmuhi/reddog-retail-demo/reddog-retail-ui:d54adef
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: VITE_SITE_TITLE
              value: Red Dog Pharmacy - Store
            - name: VITE_SITE_TYPE
              value: Pharmacy
            - name: VITE_IS_CORP
              value: 'false'
            - name: VITE_STORE_ID
              valueFrom:
                secretKeyRef:
                  name: branch.config
                  key: store_id
            - name: VITE_MAKELINE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: branch.config
                  key: makeline_base_url
            - name: VITE_ACCOUNTING_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: branch.config
                  key: accounting_base_url
