{{- if and .Values.infrastructure.sqlserver.enabled .Values.dapr.secretStore }}
apiVersion: v1
kind: Secret
metadata:
  name: reddog-sql
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  reddog-sql: "Server={{ .Values.database.host }},{{ .Values.database.port }};Database={{ .Values.database.name }};User Id={{ .Values.database.username }};Password={{ .Values.infrastructure.sqlserver.saPassword }};TrustServerCertificate=True;Encrypt=False;"
{{- end }}
