{{- if .Values.infrastructure.sqlserver.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.passwordSecret.name }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  {{ .Values.database.passwordSecret.key }}: {{ .Values.infrastructure.sqlserver.saPassword | quote }}
{{- end }}
